export const choices = {
  yesOrNo: ["", "Yes", "No"],
  gender: ["", "Male", "Female"],
  maritial: [
    "",
    "Single",
    "Married",
    "Divorced",
    "Widowed",
    "Separated",
    "Annulled"
  ],
  typeOfPetition: ["", "Bachelor", "Master", "Chile/Singapore", "Exempt"],
  highestEducation: [
    "",
    "Associate's degree",
    "Bachelor's degree",
    "Master's degree",
    "Doctorate degree"
  ],

  statusLastEntry: [
    "",
    "B1 - TEMPORARY VISITOR FOR BUSINESS",
    "B2 - TEMPORARY VISITOR FOR PLEASURE",
    "F1 - STUDENT - ACADEMIC",
    "F2 - SPOUSE-CHILD OF F-1",
    "H1B - SPECIALITY OCCUPATION",
    "H1C - NURSE RELIEF",
    "H4 - SPS OR CHLD OF H1,H2,H3 OR H2R",
    "J1 - EXCHANGE VISITOR - OTHERS",
    "J1S - EXCHANGE VISITOR - STUDENT",
    "J2 - SPOUSE-CHILD OF J-1",
    "J2S - SPOUSE-CHILD OF J-1S",
    "L1 - INTRA-COMPANY TRANSFEREE",
    "L1A - MANAGER OR EXECUTIVE",
    "L1B - SPECIALIZED KNOWLEDGE ALIEN",
    "L2 - SPOUSE-CHILD OF L-1",
    "O1 - ALIEN W-EXTRAORDINARY ABILITY",
    "O1A - EXTRAORDINARY ALIEN - NON-ARTS",
    "O1B - EXTRAORDINARY ALIEN IN ARTS",
    "O2 - ACCOMPANYING ALIEN TO O1",
    "O3 - SPOUSE-CHILD OF O-1, O-2"
  ],
  eligibilityCategory: [
    "",
    "a 5",
    "c 3 A",
    "c 3 B",
    "c 3 C",
    "c 8",
    "c 9",
    "c 26"
  ],
  units: ["", "Apt", "Ste", "Flr"],
  wage: ["", "Hour", "Week", "Month", "Year"],
  allBenefitsReceived: [
    "Cash Assistance",
    "SSI",
    "TANF",
    "GA",
    "Food Stamps",
    "Housing Assistance",
    "Rental Assistance",
    "Public Housing",
    "Federal Medicaid"
  ],
  benefitsExempt: [
    "US Armed Force",
    "Spouse Child in US Armed Force",
    "Armed Force when Receive",
    "PCGI Exempt",
    "PCGI Waiver",
    "Child for N600K",
    "None of Above"
  ],
  medicaidExempt: [
    "Emergency",
    "IDEA",
    "School Based",
    "Under 21",
    "60Days following End of Pregnancy"
  ],
  I131ApplicationType: [
    "",
    "1_a_PR_ReentryPermit",
    "1_d_TemporaryForeignTravel"
  ],
  CitizenOrPR: ["", "US Citizen", "Permanent Resident"],
  AcquireCitizenshipThrough: ["", "Birth In US", "Naturalization", "Parents"],
  Ethnicity: ["", "Hispanic or Latino", "Not Hispanic or Latino"],
  EyeColor: [
    "",
    "Black",
    "Blue",
    "Brown",
    "Gray",
    "Green",
    "Hazel",
    "Maroon",
    "Pink",
    "Unknown/Other"
  ],
  HairColor: [
    "",
    "Bald (No hair)",
    "Black",
    "Blond",
    "Brown",
    "Gray",
    "Red",
    "Sandy",
    "White",
    "Unknown/Other"
  ],
  I130ApplyFor: ["", "Spouse", "Parent", "Brother/Sister", "Child"],
  I130ChildParentRelationship: [
    "",
    "Child Born When Parents Married",
    "StepChild/Stepparent",
    "Child Born When Parents Not Married",
    "Child was Adopted"
  ],
  states: [
    "",
    "AA",
    "AE",
    "AK",
    "AL",
    "AP",
    "AR",
    "AS",
    "AZ",
    "CA",
    "CO",
    "CT",
    "DC",
    "DE",
    "FL",
    "FM",
    "GA",
    "GU",
    "HI",
    "IA",
    "ID",
    "IL",
    "IN",
    "KS",
    "KY",
    "LA",
    "MA",
    "MD",
    "ME",
    "MH",
    "MI",
    "MN",
    "MO",
    "MP",
    "MS",
    "MT",
    "NC",
    "ND",
    "NE",
    "NH",
    "NJ",
    "NM",
    "NV",
    "NY",
    "OH",
    "OK",
    "OR",
    "PA",
    "PR",
    "PW",
    "RI",
    "SC",
    "SD",
    "TN",
    "TX",
    "UT",
    "VA",
    "VI",
    "VT",
    "WA",
    "WI",
    "WV",
    "WY"
  ]

  //  yesOrNo: [{ value: "" }, { value: "Yes" }, { value: "No" }]
};
